# /*----------------------------------------------------------------------------8
# |                                                                            |
# |                      Playbook for HANA DB Install                           |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---

# Steps:
#   01) NFS: Mount
#

- hosts:          "{{ sap_sid|upper }}_DB"

  name:           DB Installation prechecks - Oracle
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    root
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults


  tasks:
# -------------------------------------+---------------------------------------8
#
# Build the list of tasks to be executed in order here. 
#
# -------------------------------------+---------------------------------------8

  - ansible.builtin.set_fact:
      tier:     ora                                                        # Actions for Oracle DB Servers
#      node_tier: oracle
    tags:
      - always

# -------------------------------------+---------------------------------------8
# Role: oracle-users
#
# Description: Create oracle users and groups.
#              
#
  - include_role:
      name:     roles-os/1.11-accounts
# -------------------------------------+---------------------------------------8
# -------------------------------------+---------------------------------------8
# Role: sap-mounts
#
# Description: Mount Filesystems
#              Mount NFS Filesystems
#
  - include_role:
      name:     roles-sap-os/2.6-sap-mounts
# -------------------------------------+---------------------------------------8


# Oracle installation has to be done with oracle user. Change the user to become orasid and call the installer.

- hosts:          "{{ anydb_sid|upper }}_DB"

  name:           DB Installation - Oracle
  remote_user:    "{{ orchestration_ansible_user }}"                
  become:         yes
  become_user:    "oracle"
  gather_facts:   true
  vars_files:
    - vars/ansible-input-api.yaml                               # API Input template with defaults

  tasks:
  - include_role:
      name:     roles-db/4.1.0-ora-install
    when:     node_tier == "oracle"
      
  - include_role:
      name:     roles-db/4.1.3-ora-msid
    when:     node_tier == "oracle-msid"

# # Oracle Post installation scripts
# - hosts:          "{{ sap_sid|upper }}_DB"

#   name:           DB Installation - Oracle
#   remote_user:    "{{ orchestration_ansible_user }}"                
#   become:         yes
#   become_user:    root
#   gather_facts:   true
#   vars_files:
#     - vars/ansible-input-api.yaml                               # API Input template with defaults

#   tasks:
#   - include_role:
#       name:     roles-db/4.1.0-ora-post-install


