---
- name: Gather Logical volumes created in 1.5
  include_vars: disks_config.yml

# Mount Filesystems
- name:     "Collecting Oracle Filesystems"
  ansible.builtin.set_fact: 
  ora-mounts: "{{ dev_path_from_lv_item }}"
  
  loop: "{{ logical_volumes }}"
  when:
      - item.tier == "ora"
      - item.node_tier == "oracle" 
      - item.fstype == "xfs"
      


# Mount Filesystems
- name:     "Mount Filesystems"
  mount:
    src:    "{{ item.src }}"
    path:   "{{ item.path }}"
    fstype: "{{ item.type }}"
    opts:   defaults
    state:  mounted
  vars:
    # Get all the hostnames in <SID>_SCS group and return only the first hostname
    nfs_server:   "{{ query('inventory_hostnames', '{{ sap_sid|upper }}_SCS') | first }}"
  loop:
    - { tier: 'all',          type: 'xfs',   src: '/dev/vg_sap/lv_usrsap',                         path: '/usr/sap' }
    - { tier: 'preparation',  type: 'xfs',   src: '/dev/vg_sap/lv_usrsapinstall',                  path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    - { tier: 'preparation',  type: 'xfs',   src: '/dev/vg_sap/lv_sapmnt',                         path: '/sapmnt' }
    - { tier: 'hdb',          type: 'xfs',   src: '/dev/vg_sap/lv_hana_shared',                    path: '/hana/shared' }
    - { tier: 'hdb',          type: 'xfs',   src: '/dev/vg_hana_data/lv_hana_data',                path: '/hana/data' }
    - { tier: 'hdb',          type: 'xfs',   src: '/dev/vg_hana_log/lv_hana_log',                  path: '/hana/log' }
    - { tier: 'hdb',          type: 'xfs',   src: '/dev/vg_hana_backup/lv_hana_backup',            path: '/hana/backup' }
    - { tier: 'web',          type: 'xfs',   src: '/dev/vg_sap/lv_sapmnt',                         path: '/sapmnt' }
    - { tier: 'dbload',       type: 'nfs4',  src: '{{ nfs_server }}:/sapmnt/{{ sap_sid|upper }}',  path: '/sapmnt/{{ sap_sid|upper }}' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle/lv_oracle',                      path: '/oracle' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_sapdata1/lv_oracle_sapdata1',    path: '/oracle/{{ anydb_sid|upper }}/sapdata1' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_sapdata1/lv_oracle_sapdata2',    path: '/oracle/{{ anydb_sid|upper }}/sapdata2' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_sapdata1/lv_oracle_sapdata3',    path: '/oracle/{{ anydb_sid|upper }}/sapdata3' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_origlogA/lv_oracle_origlogA',    path: '/oracle/{{ anydb_sid|upper }}/origlogA' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_origlogA/lv_oracle_origlogB',    path: '/oracle/{{ anydb_sid|upper }}/origlogB' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_mirrlogA/lv_oracle_mirrlogA',    path: '/oracle/{{ anydb_sid|upper }}/mirlogA' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_mirrlogA/lv_oracle_mirrlogB',    path: '/oracle/{{ anydb_sid|upper }}/mirlogB' }
    # - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_oraarch/lv_oracle_oraarch',      path: '/oracle/{{ anydb_sid|upper }}/oraarch' }
    - { tier: 'app',          type: 'nfs4',  src: '{{ nfs_server }}:/sapmnt/{{ sap_sid|upper }}',  path: '/sapmnt/{{ sap_sid|upper }}' }
    - { tier: 'hdb',          type: 'nfs4',  src: '{{ nfs_server }}:/usr/sap/install',             path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    - { tier: 'dbload',       type: 'nfs4',  src: '{{ nfs_server }}:/usr/sap/install',             path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    - { tier: 'app',          type: 'nfs4',  src: '{{ nfs_server }}:/usr/sap/install',             path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
    - { tier: 'web',          type: 'nfs4',  src: '{{ nfs_server }}:/usr/sap/install',             path: '/usr/sap/install' }                # Special Install Structure; Destroy on Completion
  when:         item.tier == "all" or
                item.tier == tier

- name:     "Mount Oracle Filesystems"
  mount:
    src:    "{{ item.scr }}"
    path:   "{{ item.src.path }}"
    fstype: "{{ item.type }}"
    opts:   defaults
    state:  mounted
  loop: 
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle/lv_oracle',                      path: '/oracle' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_sapdata1/lv_oracle_sapdata1',    path: '/oracle/{{ anydb_sid|upper }}/sapdata1' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_sapdata1/lv_oracle_sapdata2',    path: '/oracle/{{ anydb_sid|upper }}/sapdata2' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_sapdata1/lv_oracle_sapdata3',    path: '/oracle/{{ anydb_sid|upper }}/sapdata3' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_origlogA/lv_oracle_origlogA',    path: '/oracle/{{ anydb_sid|upper }}/origlogA' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_origlogA/lv_oracle_origlogB',    path: '/oracle/{{ anydb_sid|upper }}/origlogB' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_mirrlogA/lv_oracle_mirrlogA',    path: '/oracle/{{ anydb_sid|upper }}/mirlogA' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_mirrlogA/lv_oracle_mirrlogB',    path: '/oracle/{{ anydb_sid|upper }}/mirlogB' }
   - { tier: 'ora',          type: 'xfs',   src: '/dev/vg_oracle_oraarch/lv_oracle_oraarch',      path: '/oracle/{{ anydb_sid|upper }}/oraarch' }
  when:  
      item.src in "{{ ora-mounts }}" or 
      item.tier == ora
      
...
