---

- name: Gather Logical volumes created in 1.5
  include_vars: disks_config.yml
   



- name: Check if LVs exists.
  stat:
    path: "{{ dev_path_from_lv_item }}"
  loop: "{{logical_volumes }}"
  register: oravgstat

- debug:
    var:                         oravgstat

- name: Gater existing LVs 
  set_fact:
    lvexists: "{{ oravgstat.results | selectattr('stat.exists','equalto',true) | map(attribute='item.lv') |list }}" 


- debug:
    var:                         lvexists

#- fail: msg="here"

# Mount Filesystems
- name:     "Mount Filesystems for Oracle"
  mount:
    src:    "{{ dev_path_from_lv_item }}"
    #path:   "{{ ['/'~item.lv|split('_')[-2], anydb_sid|upper, item.lv|split('_')[-1]] | join('/') }}"
    path: >-
        {%- set lv_parts = item.lv.split('_') -%}
        {%- if lv_parts| length == 2 -%}
        {%- set _path = '/' ~ lv_parts[-1] -%}
        {%- else -%}
        {%- set _path = ['/' ~ lv_parts[-2], anydb_sid | upper, lv_parts[-1]] | join('/') -%}
        {%- endif -%}
        {{- _path -}} 
    fstype: "{{ item.fstype }}"
    opts:   defaults
    state:  mounted


  loop: "{{logical_volumes |sort(attribute='lv') }}"
  
    
  when:         
              #- item.tier == "ora"
              - item.node_tier == "oracle" 
              - item.lv in  lvexists
  
  register:  oraclefilesystemmounts

# orasid should be the owner of the file systems /oracle directories.
- name:              "Make orasid:dba as owners"          
  ansible.builtin.shell: |
                      chown -R ora{{ sap_sid|lower }}:dba /oracle
                      chmod -R 777 /usr/sap/install/oraserver/

#Debug for testing
- name:                           "Print oracle filesystems"
  debug:
    var:                         oraclefilesystemmounts