---
# API Input template with defaults

# Example of passing input YAML to ansible-playbook
#
#         ansible-playbook                                                                                                \
#           --inventory   new-hosts.yaml                                                                                  \
#           --user        azureadm                                                                                        \
#           --private-key sshkey                                                                                          \
#           --extra-vars="@sap-parameters.yaml"                                                                           \
#           ~/Azure_SAP_Automated_Deployment/centiq-sap-hana/deploy/ansible/${playbook}

# OS Config Settings variables
chrony_pool:                  ""
chrony_servers:               []

# BoM Processing variables
sapbits_location_base_path:   ""                                                        # REQUIRED
sapbits_bom_files:            "sapfiles"                                                # Default
bom_base_name:                ""                                                        # REQUIRED
target_media_location:        "/usr/sap/install"                                        # Default
sapbits_sas_token:            ""                                                        # Optional
sapbits_access_key:           ""                                                        # Optional
S_user:                       ""
S_password:                   ""
download_directory:           "/mnt/downloads"

# SAP Configuration for templates and install
aas_hostname:                 ""
aas_instance_number:          ""
sap_sid:                      ""                                                        # REQUIRED - SAP Install
download_basket_dir:          "{{ target_media_location }}/download_basket"
hdb_hostname:                 ""
hdb_sid:                      "HDB"                                                     # Default
hdb_instance_number:          "00"                                                      # Default
pas_hostname:                 ""
pas_instance_number:          "00"
password_hana_system:         ""
password_master:              ""                                                        # SAP Install
sap_fqdn:                     ""                                                        # SAP Install
sapadm_uid:                   2100
sapinst_gid:                  2001
sapsys_gid:                   2000
ora_sid:                      "DEV" 
dba_gid:                      3000
oper_gid:                     3001
asmoper_gid:                  3002
asmadmin_gid:                 3003
asmdba_gid:                   3004
oinstall_gid:                 3005
anydb_sid:                    "DEV"
orasid_uid:                   3000
oracle_uid:                   3001                                                      #AnyDB sid eg: Oracle,SQL,DB2
scs_hostname:                 ""
scs_instance_number:          "00"                                                      # SAP Install
sidadm_uid:                   2000
hdbadm_uid:                   2200
scs_lb_ip:                    ""                                                        # SAP HA   
db_lb_ip:                     ""                                                        # SAP HA

orchestration_ansible_user:   azureadm

password_cockpit_admin:       ""
password_db_systemdb:         ""
password_ha_db_cluster:       ""
password_os_sapadm:           ""
password_os_sidadm:           ""
password_db_xsa_admin:        ""

download_templates:           false
prometheus:                   false                                                      # Install Prometheus Monitoring Agent


sap_swap:
  - { tier: 'scs',  swap_size_mb: '4096' }
  - { tier: 'ers',  swap_size_mb: '4096' }
  - { tier: 'pas',  swap_size_mb: '20480' }
  - { tier: 'app',  swap_size_mb: '20480' }
  - { tier: 'web',  swap_size_mb: '4096' }
  - { tier: 'hana', swap_size_mb: '2048' }
  - { tier: 'oracle', swap_size_mb: '20480' }


...
