#   SAP: Register BOM
#   Prepare ASM Disks
#   Run the Oracle universal installer in silent mode. Refer to SAP Note : 2660017 Oracle Software Installation on Unix
#

# TODO: Considerations
#         15G+ swap space for Oracle DB installation.
#         message server acl
#         certificates
#         secure storage key
#

---

- name:  
  ansible.builtin.set_fact:
    dir_params:                   "{{ target_media_location }}/.params"


- name:                                Load the disk configuration settings
  ansible.builtin.include_vars:        disks_config_asm.yml

#   0x) Create hidden directory for parameter files
- name:     "Create hidden directory"
  ansible.builtin.file:
    path:   "{{ item.path }}"
    state:  directory
    mode:   0755
  loop:
    - { state: 'directory', mode: '0755', path: '{{ dir_params }}' }

- name:     "Create run flag directory"
  ansible.builtin.file:
    path:   /etc/sap_deployment_automation/oracle
    state:  directory
    mode:   0755
    owner:  oracle
    group:  oinstall

- name:     "Create Grid software directory"
  ansible.builtin.file:
    path:   /oracle/stage/{{ anydb_release }}/grid_home
    state:  directory
    owner:  oracle
    group:  oinstall



- name:               "Permission for Grid software Directory"
  become:             yes
  become_user:        root
  ansible.builtin.shell: |
                        set -o errexit
                        chown -R oracle:oinstall /oracle/*
  args:
    creates:            /etc/sap_deployment_automation/oracle/oraclepermupd.txt                    

- name:            "create after a directory permission changes"
  ansible.builtin.file:
    path:              "/etc/sap_deployment_automation/oracle/oraclepermupd.txt"
    state:             touch
  


#   Oracle Grid: Response file
- name:                               "SAP Oracle ASM: deploy Grid install response file"
  become:             yes
  become_user:        oracle
  ansible.builtin.template:
    src:                              ORACLE_19c_00_asm_v1_install.rsp.j2
    dest:                             "/etc/sap_deployment_automation/oracle/ORACLE_{{ anydb_release }}c_00_asm_{{ ansible_hostname }}_{{ anydb_sid }}_install.rsp"
    mode:                             0644
    force:                            true


#STEP1 Install Grid Software
# Unzipping this pakcage might have longer runtime.
- name:               "Unzip the Gridsoftware"
  become:             yes
  become_user:        oracle
  ansible.builtin.shell: |
                      set -o errexit
                      unzip -o -q -d /oracle/stage/{{ anydb_release }}/grid_home  /usr/sap/install/oraserver/LINUX_X86_64/grid_home/LINUX.X64_193000_grid_home.zip
                      mkdir /oracle/installlogs
  args:
    chdir:             /oracle/stage
    creates:           /etc/sap_deployment_automation/oracle/gridswunzip.txt


- name:            "create after a sucessfull unzip install"
  ansible.builtin.file:
    path:              "/etc/sap_deployment_automation/oracle/gridswunzip.txt"
    state:             touch


- name:               "Install CVUQDISK RPM"
  become:             yes
  become_user:        root
  ansible.builtin.shell: |
                      set -o errexit
                      yum install -y /oracle/stage/{{ anydb_release }}/grid_home/cv/rpm/cvuqdisk-1.0.10-1.rpm


#STEP2 RUN THE INSTALLATION - EXECUTE.

- name:               "Execute GRIDSETUP"
  become:             yes
  become_user:        oracle
  ansible.builtin.shell: |
                      set -o errexit
                      ./gridSetup.sh -silent -responseFile /etc/sap_deployment_automation/oracle/ORACLE_19c_00_asm_{{ ansible_hostname }}_{{ anydb_sid }}_install.rsp |tee -a /oracle/installlogs/gridinstall.log
  register:           gridinstaller_results
  #failed_when:        gridinstaller_results.rc >= 2              #installer returns rc=1 (exited with warning) by default when run is silent mode as the oratab file is created only after running the root.sh
  environment:
    CV_ASSUME_DISTID:             OL7
  args:       
    executable:        /bin/csh
    chdir:            "/oracle/stage/{{ anydb_release }}/grid_home"
    creates:           /etc/sap_deployment_automation/oracle/gridinstall.txt

- name:            "create after a sucessfull GRID install"
  ansible.builtin.file:
    path:              "/etc/sap_deployment_automation/oracle/gridinstall.txt"
    state:             touch


#STEP3 POST PROCESSING.


- name:           "Oracle Post Processing - Run root.sh"                
  become:         yes
  become_user:    root
  ansible.builtin.shell: |   
                     /oracle/oraInventory/orainstRoot.sh
                     /oracle/stage/{{ anydb_release }}/grid_home/root.sh                                    
  register: rootscript_results
  args:
    executable:       /bin/csh
    creates:          /etc/sap_deployment_automation/oracle/gridinstallrootscript.txt

- name:            "creates after a sucessfull script execution"
  ansible.builtin.file:
    path:              "/etc/sap_deployment_automation/oracle/gridinstallrootscript.txt"
    state:             touch
  

# #STEP 4  Execute Config tools.
- name:               "Execute ASM Configtools"
  become:             yes
  become_user:        oracle
  ansible.builtin.shell: |
                      set -o errexit
                      ./gridSetup.sh -executeConfigTools -silent -responseFile /etc/sap_deployment_automation/oracle/ORACLE_19c_00_asm_{{ ansible_hostname }}_{{ anydb_sid }}_install.rsp |tee -a /oracle/installlogs/asmtoolsinstall.log
  register:           toolsinstaller_results
  #failed_when:        gridinstaller_results.rc >= 2              #installer returns rc=1 (exited with warning) by default when run is silent mode as the oratab file is created only after running the root.sh
  environment:
    DB_SID:                       "{{anydb_sid}}"
    CV_ASSUME_DISTID:             OL7
  args:       
    executable:        /bin/csh
    chdir:            "/oracle/stage/{{ anydb_release }}/grid_home"
    creates:           /etc/sap_deployment_automation/oracle/asmtoolsinstall.txt

- name:            "create after a sucessfull install"
  ansible.builtin.file:
    path:              "/etc/sap_deployment_automation/oracle/asmtoolsinstall.txt"     
    state:             touch 


# #STEP 5 Create ARCH and RECO disk groups using ASMCA.

- name:           "Create ASM Disk groups ARCH and RECO"                
  become:         yes
  become_user:    oracle
  ansible.builtin.shell: |   
                     set -o errexit
                     ./asmca -silent -createDiskGroup -diskGroupName RECO -diskList '{{ recolistrsp }}1' 
                     ./asmca -silent -createDiskGroup -diskGroupName ARCH -diskList '{{ archlistrsp }}1' 
                     
  register: diskgroupcreation_results
  environment:
    DB_SID:                       "{{anydb_sid}}"
    CV_ASSUME_DISTID:             OL7
  args:
    executable:       /bin/csh
    chdir:            "/oracle/stage/{{ anydb_release }}/grid_home/bin"
    creates:          /etc/sap_deployment_automation/oracle/diskgroupcreated.txt

- name:            "creates after a sucessfull disk group creation"
  ansible.builtin.file:
    path:                "/etc/sap_deployment_automation/oracle/diskgroupcreated.txt"
    state:               touch 






# #   0x) remove hidden directory for parameter files
# - name:     "remove hidden directory"
#   ansible.builtin.file:
#     path:   "{{ item.path }}"
#     state:  "{{ item.state }}"
#     mode:   "{{ item.mode }}"
#   loop:
#     - { state: 'absent',    mode: '0755', path: '{{ dir_params }}' }

...
# /*---------------------------------------------------------------------------8
# |                                   END                                      |
# +------------------------------------4--------------------------------------*/
