---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# |               Task: 1.4       - Package lists per OS                       |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

# For each supported 'distro_id' we want a list of dictionary entries that
# specify the associated tier (or 'all' to always match), the package name,
# and whether we want the package to be installed (present) or removed
# (absent). See the definition of 'distro_id' to determine what to use when
# creating an entry for a new distribution.
packages:
    redhat7:
      - { tier: 'os',    package: '@base',                  state: 'present' }
      - { tier: 'os',    package: 'gtk2',                   state: 'present' }
      - { tier: 'os',    package: 'libicu',                 state: 'present' }
      - { tier: 'os',    package: 'xulrunner',              state: 'present' }
      - { tier: 'os',    package: 'sudo',                   state: 'present' }
      - { tier: 'os',    package: 'tcsh',                   state: 'present' }
      - { tier: 'os',    package: 'libssh2',                state: 'present' }
      - { tier: 'os',    package: 'expect',                 state: 'present' }
      - { tier: 'os',    package: 'cairo',                  state: 'present' }
      - { tier: 'os',    package: 'graphviz',               state: 'present' }
      - { tier: 'os',    package: 'iptraf-ng',              state: 'present' }
      - { tier: 'os',    package: 'krb5-workstation',       state: 'present' }
      - { tier: 'os',    package: 'krb5-libs',              state: 'present' }
      - { tier: 'os',    package: 'libpng12',               state: 'present' }
      - { tier: 'os',    package: 'nfs-utils',              state: 'present' }
      - { tier: 'os',    package: 'lm_sensors',             state: 'present' }
      - { tier: 'os',    package: 'rsyslog',                state: 'present' }
      - { tier: 'os',    package: 'openssl',                state: 'present' }
      - { tier: 'os',    package: 'PackageKit-gtk3-module', state: 'present' }
      - { tier: 'os',    package: 'libcanberra-gtk2',       state: 'present' }
      - { tier: 'os',    package: 'libtool-ltdl',           state: 'present' }
      - { tier: 'os',    package: 'xorg-x11-xauth',         state: 'present' }
      - { tier: 'os',    package: 'numactl',                state: 'present' }
      - { tier: 'os',    package: 'xfsprogs',               state: 'present' }
      - { tier: 'os',    package: 'net-tools',              state: 'present' }
      - { tier: 'os',    package: 'bind-utils',             state: 'present' }
      - { tier: 'os',    package: 'chrony',                 state: 'present' }
      - { tier: 'os',    package: 'gdisk',                  state: 'present' }
      - { tier: 'os',    package: 'sg3_utils',              state: 'present' }
      - { tier: 'os',    package: 'lvm2',                   state: 'present' }
      - { tier: 'os',    package: 'numad',                  state: 'present' }
      - { tier: 'os',    package: 'cifs-utils',             state: 'present' }
      - { tier: 'sapos', package: 'tuned-profiles-sap*',    state: 'present' } 
      - { tier: 'sapos', package: 'compat-sap-c++-*',       state: 'present' }
      - { tier: 'sapos', package: 'libatomic',              state: 'present' }
      - { tier: 'sapos', package: 'uuidd',                  state: 'present' }
      - { tier: 'sapos', package: 'csh',                    state: 'present' }     
      - { tier: 'ha',    package: 'jq',                     state: 'present' }

    redhat8:
      - { tier: 'os',    package: '@base',                  state: 'present' }
      - { tier: 'os',    package: 'gtk2',                   state: 'present' }
      - { tier: 'os',    package: 'libicu',                 state: 'present' }
      - { tier: 'os',    package: 'sudo',                   state: 'present' }
      - { tier: 'os',    package: 'tcsh',                   state: 'present' }
      - { tier: 'os',    package: 'libssh2',                state: 'present' }
      - { tier: 'os',    package: 'expect',                 state: 'present' }
      - { tier: 'os',    package: 'cairo',                  state: 'present' }
      - { tier: 'os',    package: 'graphviz',               state: 'present' }
      - { tier: 'os',    package: 'iptraf-ng',              state: 'present' }
      - { tier: 'os',    package: 'krb5-workstation',       state: 'present' }
      - { tier: 'os',    package: 'krb5-libs',              state: 'present' }
      - { tier: 'os',    package: 'libpng12',               state: 'present' }
      - { tier: 'os',    package: 'nfs-utils',              state: 'present' }
      - { tier: 'os',    package: 'lm_sensors',             state: 'present' }
      - { tier: 'os',    package: 'rsyslog',                state: 'present' }
      - { tier: 'os',    package: 'openssl',                state: 'present' }
      - { tier: 'os',    package: 'PackageKit-gtk3-module', state: 'present' }
      - { tier: 'os',    package: 'libcanberra-gtk2',       state: 'present' }
      - { tier: 'os',    package: 'libtool-ltdl',           state: 'present' }
      - { tier: 'os',    package: 'xorg-x11-xauth',         state: 'present' }
      - { tier: 'os',    package: 'numactl',                state: 'present' }
      - { tier: 'os',    package: 'xfsprogs',               state: 'present' }
      - { tier: 'os',    package: 'net-tools',              state: 'present' }
      - { tier: 'os',    package: 'bind-utils',             state: 'present' }
      - { tier: 'os',    package: 'chrony',                 state: 'present' }
      - { tier: 'os',    package: 'gdisk',                  state: 'present' }
      - { tier: 'os',    package: 'sg3_utils',              state: 'present' }
      - { tier: 'os',    package: 'lvm2',                   state: 'present' }
      - { tier: 'os',    package: 'numad',                  state: 'present' }
      - { tier: 'os',    package: 'cifs-utils',             state: 'present' }
      - { tier: 'sapos', package: 'tuned-profiles-sap*',    state: 'present' } 
      - { tier: 'sapos', package: 'compat-sap-c++-*',       state: 'present' }
      - { tier: 'sapos', package: 'libatomic',              state: 'present' }
      - { tier: 'sapos', package: 'uuidd',                  state: 'present' }
      - { tier: 'sapos', package: 'csh',                    state: 'present' }     
      - { tier: 'ha',    package: 'jq',                     state: 'present' }

    suse12:
      - { tier: 'os',    package: 'chrony',         state: 'present' }
      - { tier: 'os',    package: 'libyui-qt-pkg7', state: 'present' }
      - { tier: 'os',    package: 'glibc',          state: 'present' }
      - { tier: 'os',    package: 'systemd',        state: 'present' }
      - { tier: 'os',    package: 'tuned',          state: 'present' }
      - { tier: 'os',    package: 'numad',          state: 'present' }
      - { tier: 'os',    package: 'ntp',            state: 'absent' }
      - { tier: 'sapos', package: 'saptune',        state: 'present' }
      - { tier: 'sapos', package: 'libgcc_s1',      state: 'present' }
      - { tier: 'sapos', package: 'libstdc++6',     state: 'present' }
      - { tier: 'sapos', package: 'libatomic1',     state: 'present' }
      - { tier: 'sapos', package: 'uuidd',          state: 'present' }
      - { tier: 'ha',    package: 'jq',             state: 'present' }

    suse15:
      - { tier: 'os',    package: 'chrony',          state: 'present' }
      - { tier: 'os',    package: 'libyui-qt-pkg11', state: 'present' }
      - { tier: 'os',    package: 'glibc',           state: 'present' }
      - { tier: 'os',    package: 'systemd',         state: 'present' }
      - { tier: 'os',    package: 'tuned',           state: 'present' }
      - { tier: 'os',    package: 'numad',           state: 'present' }
      - { tier: 'os',    package: 'ntp',             state: 'absent' }
      - { tier: 'sapos', package: 'saptune',         state: 'present' }
      - { tier: 'sapos', package: 'libgcc_s1',       state: 'present' }
      - { tier: 'sapos', package: 'libstdc++6',      state: 'present' }
      - { tier: 'sapos', package: 'libatomic1',      state: 'present' }
      - { tier: 'sapos', package: 'uuidd',           state: 'present' }
      - { tier: 'ha',    package: 'jq',              state: 'present' }

      # TODO(rtamalin): Ensure SLE 15 SP2 uses /usr/bin/python3 rather
      # than /usr/bin/python.
      # Required to enable ansible to use /usr/bin/python on SLE 15 SP2
      - { tier: 'os', package: 'python2-rpm',             state: 'present' }



      #Adding packages for Oracle linux 8.4 to start with, copied the list from RHEL. 
      #Adding additional Oracle linux packages as per SAP Note 2069760 - Oracle Linux 7.x SAP Installation and Upgrade. Need to add the groupinstall command.
    oraclelinux8:
      - { tier: 'os',    package: oracle-database-preinstall-19c, state: 'present' }
      - { tier: 'os',    package: 'sudo',                         state: 'present' }
      - { tier: 'os',    package: 'tcsh',                         state: 'present' }
      - { tier: 'os',    package: 'nfs-utils',                    state: 'present' }
      - { tier: 'os',    package: 'rsyslog',                      state: 'present' }
      - { tier: 'os',    package: 'openssl',                      state: 'present' }
      - { tier: 'os',    package: 'xorg-x11-xauth',               state: 'present' }
      - { tier: 'os',    package: 'net-tools',                    state: 'present' }
      - { tier: 'os',    package: 'bind-utils',                   state: 'present' }
      - { tier: 'os',    package: 'xfsprogs',                   state: 'present' }
      - { tier: 'os',    package: 'gdisk',                        state: 'present' }
      - { tier: 'os',    package: 'lvm2',                         state: 'present' }
      - { tier: 'os',    package: 'cifs-utils',                   state: 'present' }
      - { tier: 'os',    package: 'uuidd',                        state: 'present' }
      - { tier: 'os',    package: 'csh',                          state: 'present' }    
      - { tier: 'ha',    package: 'jq',                           state: 'present' }
      - { tier: 'os',    package: 'unzip',                        state: 'present' }


    
