---
name:    'ORACLE_19_00_v0001ms'
target:  'Oracle 19c'
version: 1



materials:
#   templates:
    # - name:     X
    #   file:     HANA_2_00_055_v1.params
    #   override_target_location: "{{ target_media_location }}/config"

    # - name:     X
    #   file:     HANA_2_00_055_v1.params.xml
    #   override_target_location: "{{ target_media_location }}/config"

#   stackfiles:
    # # Download Basket permalinks
    # - name: Download Basket permalinks
    #   file: myDownloadBasketFiles.txt
    #   override_target_location: "{{ target_media_location }}/config"

  media:
    # SAPCAR 7.22
    - name:         SAPCAR
      archive:      SAPCAR_1010-70006178.EXE
      filename:     SAPCAR
      permissions:  '0755'
      download:     true
      url:          https://softwaredownloads.sap.com/file/0020000002208852020               #Note update the links

    - name:         Oracle Client
      archive:      51054541.zip
      extract:      true
      extractDir:   oraclient
      path:         download_basket
      download:     true
      #url:          https://softwaredownloads.sap.com/file/0020000000381822021               #Note update the links

    - name:         Oracle Software Server
      archive:      51053828.zip
      extract:      true
      download:     true
      extractDir:   oraserver
      path:         download_basket
      #creates:     SIGNATURE.SMF
      #url:          https://softwaredownloads.sap.com/file/0020000000958462021


#SBP Patches are downloaded based on SAP Note 2799920 - Patches 19c: Database

    - name:         "Oracle SBP - Bundle patches for 19c: GIRU"
      archive:      GIRU19P_2108-70004508.ZIP
      extract:      true
      download:     true
      extractDir:   SBP/GIRU19P
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:         https://softwaredownloads.sap.com/file/0020000001214732021

    - name:         "Oracle SBP - Bundle patches for 19c: SAP19P"
      archive:      SAP19P_2108-70004508.ZIP
      extract:      true
      download:     true
      extractDir:   SBP/SAPSBP
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000001213832021

    - name:         "Oracle SBP - Bundle patches for 19c: SBPJDK19P"
      archive:      SBPJDK19P_2108-70004508.ZIP
      extract:      true
      download:     true
      extractDir:   SBP/SBPJDK
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:         https://softwaredownloads.sap.com/file/0020000001213892021

    - name:         "Oracle SBP - Bundle patches for 19c: OPatch"
      archive:      OPATCH19P_2105-70004508.ZIP
      extract:      true
      download:     true
      extractDir:   SBP/OPATCH
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000000751692021

    - name:         "Oracle SBP - Bundle patches for 19c: Readme Patch File"
      archive:      README19P_2108-70004508.HTM
      extract:      false
      download:     false
      extractDir:   SBP
      path:         SBP
      #creates:     SIGNATURE.SMF
      url:         https://softwaredownloads.sap.com/file/0020000001213422021

#SAP Oracle executables, SWMP and Installation exports 
    
    - name:         "DB Independent Kernel Files"
      archive:      SAPEXE_200-70005283.SAR
      extract:      false
      download:     true
      path:         download_basket
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000001164152021
    
    
    - name:         "Oracle DB specific kernel files"
      archive:      SAPEXEDB_200-70005502.SAR
      extract:      false
      download:     true
      path:         download_basket
      #creates:     SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000001163822021

      # SWPM
    - name:         "SWPM20SP09 OS: Linux on x86_64 64bit"
      archive:      SWPM10SP32_5-20009701.SAR
      extract:      true
      extractDir:   SWPM
      creates:      SIGNATURE.SMF
      url:          https://softwaredownloads.sap.com/file/0020000001253802021


    - name:       "Oracle installation dump"
      archive:     51050829_3.ZIP
      extract:     true
      download:    true
      extractDir:  EXPORT
      path:        download_basket
      #creates:    SIGNATURE.SMF
      url:        https://softwaredownloads.sap.com/file/0030000000635092016
    

    - name:         "SAP Host Agent"
      archive:      SAPHOSTAGENT53_53-80004822.SAR
      extract:      false
      download:     true
      path:         download_basket
      url:          https://softwaredownloads.sap.com/file/0020000001179602021

    # - name:         X
    #   archive:      saphostagentrpm_51-20009394.rpm
    #   url:          https://softwaredownloads.sap.com/file/0020000000269152021

...
