---


- name: "Exports: Create SAP Directories"
  ansible.builtin.file:
    path:   "{{ item.path }}"
    state:  directory
    mode:   0755
  loop:
    - { path: '/usr/sap/install' }
    - { path: '/usr/sap/trans' }
    - { path: '/sapmnt/{{ sap_sid|upper }}' }
  when:
    - node_tier == 'scs'

- name: "Exports: NFS Server Config on Suse"
  ansible.builtin.lineinfile:
    path:   "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
    owner:  root
    group:  root
    mode:   0644
  loop:
    - { path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)' }
    - { path: '/etc/exports',       regexp: '^/usr/sap/install',            line: '/usr/sap/install *(rw,sync,no_wdelay,no_root_squash)' }
      # - { tier: 'preparation', path: '/etc/sysconfig/nfs', regexp: '^NFS3_SERVER_SUPPORT=',        line: 'NFS3_SERVER_SUPPORT="no"' }
    - { path: '/etc/sysconfig/nfs', regexp: '^NFS3_SERVER_SUPPORT=',        line: 'NFS3_SERVER_SUPPORT="yes"' }
    - { path: '/etc/sysconfig/nfs', regexp: '^NFS4_SUPPORT=',               line: 'NFS4_SUPPORT="yes"' }
  when:
    - (ansible_os_family|upper == "SUSE" or (ansible_os_family|lower ~ ansible_distribution_major_version) == "redhat7")
    - node_tier == 'scs'

- name: "Exports: NFS Server Config on Suse (sapmnt)"
  ansible.builtin.lineinfile:
    path:   "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
    owner:  root
    group:  root
    mode:   0644
  loop:
    - { path: '/etc/exports',       regexp: '^/sapmnt/{{ sap_sid|upper }}', line: '/sapmnt/{{ sap_sid|upper }} *(rw,sync,no_wdelay,no_root_squash)' }
  when:
    - (ansible_os_family|upper == "SUSE" or (ansible_os_family|lower ~ ansible_distribution_major_version) == "redhat7")
    - node_tier == 'scs'
    - sap_mnt is not defined

- name: "Exports: NFS Server Config on  : {{ ansible_distribution|lower ~ ansible_distribution_major_version }}"
  ansible.builtin.lineinfile:
    path:   "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
    owner:  root
    group:  root
    mode:   0644
  loop:
    - { path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)'              }
    - { path: '/etc/exports',       regexp: '^/usr/sap/install',            line: '/usr/sap/install *(rw,sync,no_wdelay,no_root_squash)'            }
    - { path: '/etc/nfs.conf',      regexp: '^# vers3=',                    line: ' vers3=y'                                                        }
    - { path: '/etc/nfs.conf',      regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
    - { path: '/etc/nfs.conf',      regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
  when:
    - (ansible_os_family|lower ~ ansible_distribution_major_version) == "redhat8"
    - node_tier == 'scs'

- name: "Exports: NFS Server Config on  : {{ ansible_distribution|lower ~ ansible_distribution_major_version }} (sapmnt)"
  ansible.builtin.lineinfile:
    path:   "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
    owner:  root
    group:  root
    mode:   0644
  loop:
    - { path: '/etc/exports',       regexp: '^/sapmnt/{{ sap_sid|upper }}', line: '/sapmnt/{{ sap_sid|upper }} *(rw,sync,no_wdelay,no_root_squash)' }
  when:
    - (ansible_distribution|lower ~ ansible_distribution_major_version) == "redhat8"
    - node_tier == 'scs'
    - sap_mnt is not defined


- name: "Exports: NFS Server Config on Oracle Linux 8"
  ansible.builtin.lineinfile:
    path:   "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
    owner:  root
    group:  root
    mode:   0644
  loop:
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/sapmnt/{{ sap_sid|upper }}', line: '/sapmnt/{{ sap_sid|upper }} *(rw,sync,no_wdelay,no_root_squash)' }
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)'              }
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/usr/sap/install',            line: '/usr/sap/install *(rw,sync,no_wdelay,no_root_squash)'            }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers3=',                    line: ' vers3=n'                                                        }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
  when:     
    - (ansible_distribution|lower ~ ansible_distribution_major_version) == "oraclelinux8" 
    - node_tier == 'scs'
    - sap_mnt is not defined
    - MULTI_SID is not defined


- name: "Exports: NFS Server Config on Oracle Linux 8 for oracle Multi-SID installation"
  ansible.builtin.lineinfile:
    path:   "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line:   "{{ item.line }}"
    owner:  root
    group:  root
    mode:   0644
  loop:
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/usr/sap/trans',              line: '/usr/sap/trans *(rw,sync,no_wdelay,no_root_squash)'              }
    - { tier: 'preparation', path: '/etc/exports',       regexp: '^/usr/sap/install',            line: '/usr/sap/install *(rw,sync,no_wdelay,no_root_squash)'            }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers3=',                    line: ' vers3=n'                                                        }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.1=',                  line: ' vers4.1=y'                                                      }
    - { tier: 'preparation', path: '/etc/nfs.conf',      regexp: '^# vers4.2=',                  line: ' vers4.2=y'                                                      }
  when:     
    - (ansible_distribution|lower ~ ansible_distribution_major_version) == "oraclelinux8" 
    - node_tier == 'scs'
    - sap_mnt is not defined
    - MULTI_SID is defined


- name: "Exports: NFS Server Config on Oracle Linux 8 for Multi-SID installation "
  ansible.builtin.lineinfile:
    path:   "/etc/exports"
    regexp: "^/sapmnt/{{ item.sid|upper }}"
    line:   "/sapmnt/{{ item.sid|upper }} *(rw,sync,no_wdelay,no_root_squash)"
    owner:  root
    group:  root
    mode:   0644
  loop: "{{ MULTI_SID }}"
  when:     
    - (ansible_distribution|lower ~ ansible_distribution_major_version) == "oraclelinux8" 
    - node_tier == 'scs'
    - sap_mnt is not defined
    - MULTI_SID is defined